//
// Generated by Bluespec Compiler, version 2021.07-10-gb37e90ec (build b37e90ec)
//
// On Tue Nov  2 14:48:16 CST 2021
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module adderTb(CLK,
	       RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule ifc
  wire [31 : 0] ifc$sum, ifc$sum_x, ifc$sum_y, ifc$sum_z;

  // submodule ifc
  mkIfcIns ifc(.CLK(CLK),
	       .RST_N(RST_N),
	       .sum_x(ifc$sum_x),
	       .sum_y(ifc$sum_y),
	       .sum_z(ifc$sum_z),
	       .sum(ifc$sum),
	       .RDY_sum());

  // submodule ifc
  assign ifc$sum_x = 32'd2 ;
  assign ifc$sum_y = 32'd3 ;
  assign ifc$sum_z = 32'd4 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    $display("Answer is %d", $signed(ifc$sum));
    $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // adderTb

