//
// Generated by Bluespec Compiler, version 2021.07-10-gb37e90ec (build b37e90ec)
//
// On Tue Nov  2 14:48:16 CST 2021
//
//
// Ports:
// Name                         I/O  size props
// sum                            O    32
// RDY_sum                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// sum_x                          I    32
// sum_y                          I    32
// sum_z                          I    32
//
// Combinational paths from inputs to outputs:
//   (sum_x, sum_y, sum_z) -> sum
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkIfcIns(CLK,
		RST_N,

		sum_x,
		sum_y,
		sum_z,
		sum,
		RDY_sum);
  input  CLK;
  input  RST_N;

  // value method sum
  input  [31 : 0] sum_x;
  input  [31 : 0] sum_y;
  input  [31 : 0] sum_z;
  output [31 : 0] sum;
  output RDY_sum;

  // signals for module outputs
  wire [31 : 0] sum;
  wire RDY_sum;

  // value method sum
  assign sum = sum_x + sum_y + sum_z ;
  assign RDY_sum = 1'd1 ;
endmodule  // mkIfcIns

