//
// Generated by Bluespec Compiler, version 2021.07-10-gb37e90ec (build b37e90ec)
//
// On Thu Nov 11 14:48:17 CST 2021
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module compositionTb(CLK,
		     RST_N);
  input  CLK;
  input  RST_N;

  // register x1
  reg [31 : 0] x1;
  wire [31 : 0] x1$D_IN;
  wire x1$EN;

  // register x2
  reg [31 : 0] x2;
  wire [31 : 0] x2$D_IN;
  wire x2$EN;

  // register y1
  reg [31 : 0] y1;
  wire [31 : 0] y1$D_IN;
  wire y1$EN;

  // register y2
  reg [31 : 0] y2;
  wire [31 : 0] y2$D_IN;
  wire y2$EN;

  // register x1
  assign x1$D_IN = y1 + 32'd1 ;
  assign x1$EN = 1'd1 ;

  // register x2
  assign x2$D_IN = y2 + 32'd1 ;
  assign x2$EN = 1'd1 ;

  // register y1
  assign y1$D_IN = x1 + 32'd1 ;
  assign y1$EN = 1'd1 ;

  // register y2
  assign y2$D_IN = x2 + 32'd1 ;
  assign y2$EN = 1'b0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        x1 <= `BSV_ASSIGNMENT_DELAY 32'd10;
	x2 <= `BSV_ASSIGNMENT_DELAY 32'd10;
	y1 <= `BSV_ASSIGNMENT_DELAY 32'd100;
	y2 <= `BSV_ASSIGNMENT_DELAY 32'd100;
      end
    else
      begin
        if (x1$EN) x1 <= `BSV_ASSIGNMENT_DELAY x1$D_IN;
	if (x2$EN) x2 <= `BSV_ASSIGNMENT_DELAY x2$D_IN;
	if (y1$EN) y1 <= `BSV_ASSIGNMENT_DELAY y1$D_IN;
	if (y2$EN) y2 <= `BSV_ASSIGNMENT_DELAY y2$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    x1 = 32'hAAAAAAAA;
    x2 = 32'hAAAAAAAA;
    y1 = 32'hAAAAAAAA;
    y2 = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      $display("x1,y1 = %0d,%0d; x2,y2 = %0d,%0d;",
	       $signed(x1),
	       $signed(y1),
	       $signed(x2),
	       $signed(y2));
    if (RST_N != `BSV_RESET_VALUE)
      if ((x1 ^ 32'h80000000) >= 32'h80000069) $finish(32'd1);
    if (RST_N != `BSV_RESET_VALUE) $display("r1");
    if (RST_N != `BSV_RESET_VALUE) $display("r2a");
  end
  // synopsys translate_on
endmodule  // compositionTb

