//
// Generated by Bluespec Compiler, version 2021.07-10-gb37e90ec (build b37e90ec)
//
// On Sun Nov  7 16:24:47 CST 2021
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module circuitsTb(CLK,
		  RST_N);
  input  CLK;
  input  RST_N;

  // register cycle
  reg [31 : 0] cycle;
  wire [31 : 0] cycle$D_IN;
  wire cycle$EN;

  // remaining internal signals
  wire [31 : 0] IF_cycle_BIT_0_THEN_97_ELSE_96___d9;

  // register cycle
  assign cycle$D_IN = cycle + 32'd1 ;
  assign cycle$EN = 1'd1 ;

  // remaining internal signals
  assign IF_cycle_BIT_0_THEN_97_ELSE_96___d9 = cycle[0] ? 32'd97 : 32'd96 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cycle <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (cycle$EN) cycle <= `BSV_ASSIGNMENT_DELAY cycle$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cycle = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      $display("%0d, rule r, a = %0d",
	       $signed(cycle),
	       $signed(((cycle[1:0] == 2'd3) ?
			  IF_cycle_BIT_0_THEN_97_ELSE_96___d9 + 32'd3 :
			  IF_cycle_BIT_0_THEN_97_ELSE_96___d9) +
		       32'd7));
    if (RST_N != `BSV_RESET_VALUE)
      if ((cycle ^ 32'h80000000) > 32'h80000007) $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // circuitsTb

